version: '3.9'

networks:
  app-tier:
    driver: bridge

volumes:
  storage:

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - storage:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-tier

  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-tier
  