version: '3.9'


volumes:
  storage:

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - storage:/var/lib/mysql
    env_file:
      - .env

  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  